steps:
  - name: gcr.io/cloud-builders/git
    args:
      - clone
      - 'https://github.com/duetailabs/workstation.git'
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - $_IMAGE_URL
      - workstation
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_IMAGE_URL
images:
  - '$_IMAGE_URL'
options:
  logging: CLOUD_LOGGING_ONLY
  dynamicSubstitutions: true
substitutions:
  _IMAGE_URL: 'us-central1-docker.pkg.dev/$PROJECT_ID/demo/demo-workstation:latest'
